project_four/app_four/urls.py
from django.conf.urls import url
from app_four import views

#template tagging
app_name = 'app_four'

urlpatterns = [
    url(r'^info/$', views.info, name='info'),
    url(r'^other/$', views.other, name='other')
]

project_four/project_four/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app_four import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app_four.urls'))
]

project_four/app_four/models.py
from django.db import models

# Create your models here.

project_four/app_four/views.py
from django.shortcuts import render

def index(req):
    context_dict = {
                    'text': 'hello world',
                    'number': 100
                    }

    return render(req, 'app_four/index.html', context_dict)

def other(req):
    return render(req, 'app_four/other.html')

def info(req):
    return render(req, 'app_four/url_info.html')

project_four/templates/app_four/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'index' %}">Home</a>
          <a class="nav-item nav-link" href="{% url 'app_four:info' %}">Info</a>
          <a class="nav-item nav-link" href="{% url 'app_four:other' %}">Other</a>
        </div>
      </div>
    </nav>

    <div class="container">

      {% block body_block%}

      {% endblock %}

    </div>

  </body>
</html>

project_four/templates/app_four/index.html
<!DOCTYPE html>
{% extends "app_four/base.html" %}
  {% load my_pipes %}
  {% block body_block %}

    <h1>Home</h1>
    <hr>
    <p>{{ text|cut:'hell' }}</p>
    <p>{{ number|add:"3" }}</p>

  {% endblock %}

project_four/templates/app_four/other.html
<!DOCTYPE html>
{% extends "app_four/base.html" %}

  {% block body_block %}

    <h1>Other</h1>
    <!-- <a href="{% url 'app_four:info' %}">Info</a>
    <a href="{% url 'admin:index' %}">Admin</a>
    <a href="{% url 'index' %}">Home</a> -->

  {% endblock %}

project_four/templates/app_four/url_info.html
<!DOCTYPE html>
{% extends "app_four/base.html" %}

  {% block body_block %}

    <h1>Info</h1>
    <!-- <a href="{% url 'app_four:other' %}">Other</a> -->

  {% endblock %}