project_five/app_five/urls.py
from django.conf.urls import url
from app_five import views

# SET THE NAMESPACE!
app_name = 'app_five'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$', views.user_login, name='user_login')
]

project_five/project_five/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app_five import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^app_five/',include('app_five.urls')),
    url(r'^logout/$', views.user_logout, name='logout')
]

project_five/app_five/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

project_five/app_five/forms.py
from django import forms
from django.contrib.auth.models import User
from app_five.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

project_five/app_five/views.py
from django.shortcuts import render
from app_five.forms import UserForm, UserProfileInfoForm

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

def index(req):
    return render(req, 'app_five/index.html')

@login_required
def user_logout(req):
    logout(req)
    return HttpResponseRedirect(reverse('index'))

def register(req):

    registered = False

    if req.method == 'POST':
        user_form = UserForm(data=req.POST)
        profile_form = UserProfileInfoForm(data=req.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in req.FILES:
                profile.profile_pic = req.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    context_dict = {
                    'user_form': user_form,
                    'profile_form': profile_form,
                    'registered': registered
                    }
    print('registered: ', registered)
    return render(req, 'app_five/registration.html', context=context_dict)

def user_login(req):

    if req.method == 'POST':
        username = req.POST.get('username')
        password = req.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(req, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Accout Inactive')
        else:
            print('Failed login: {}'.format(username))
            return HttpResponse('invalid login')

    else:
        return render(req, 'app_five/login.html', {})

project_five/templates/app_five/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Auth Project</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app_five:register' %}">Register</a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
              <a class="nav-link" href="{% url 'app_five:user_login' %}">Login</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

project_five/templates/app_five/index.html
{% extends "app_five/base.html" %}
{% block body_block %}

  <h2>Home</h2>

{% endblock %}

project_five/templates/app_five/login.html
{% extends 'app_five/base.html' %}
{% block body_block %}

<div class="jumbtron">
  <h1>Login</h1>

  <form action="{% url 'app_five:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password</label>
    <input type="password" name="password">

    <input type="submit" value="Submit">
  </form>

</div>
{% endblock %}

project_five/templates/app_five/registration.html
{% extends "app_five/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="jumbotron">
    {% if registered %}

      <h1>Thank you</h1>

    {% else %}

      <h1>Register Here:</h1>
      <hr>

      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register">
      </form>

    {% endif %}

  </div>
{% endblock %}